# -----------------------------------------------------------------------------------
# SET PATH VARIABLES
# -----------------------------------------------------------------------------------


data path : data/run_ID_X.pkl
splits path : splits/run_ID_X_splits.pkl

dataset name : &dataname run_IX_X
main results folder : &mainsavepath modeling_results/
models folder path : !join [*mainsavepath, *dataname, /models]
parameters folder path : !join [*mainsavepath, *dataname, /parameters]
importance folder path : !join [*mainsavepath, *dataname, /feature_importance_values]
scores folder path : !join [*mainsavepath, *dataname, /performance_scores]
figures folder path : !join [*mainsavepath, *dataname, /figures]

# -----------------------------------------------------------------------------------
# SET IMPLEMENTATION VARIABLES
# -----------------------------------------------------------------------------------

# 1. Data properties ----------------------------------------------------------------

features:
  age_clin : age
  GCS_clin : GCS
  Sex_clin : sex
  Pup_clin : pupil status



# 2. Modeling Properties ------------------------------------------------------------

impute data : Yes

imputation type : mean/mode

models to use :
  - GLM
  - Lasso
  - ElasticNet
  - Catboost
  - MLP
  - SVMC
  - NB

test size : 0.2

number of splits :  2

final performance measures :
  - AUC
  - accuracy
  - average_class_accuracy
  - f1

subsampling to use :
  - none

fixed hyperparameters:
  SVMC :
    C : 1.0
    kernel : 'rbf'
    degree : 3
    gamma : 'auto'
    coef0 : 0.0
    shrinking : yes
    probability : yes
    tol : 0.001
    cache_size : 200
    verbose : no
    max_iter : -1
    decision_function_shape : 'ovr'

  SVMR :
    C : 1.0
    kernel : 'rbf'
    degree : 3
    gamma : 'auto'
    coef0 : 0.0
    shrinking : yes
    tol : 0.001
    cache_size : 200
    verbose : no
    max_iter : -1

  NB :
    var_smoothing : 0.000000001

  GLM :
    C : 100000000000000
    fit_intercept : no
    penalty : l1
    solver : saga
    tol : 0.001
    max_iter : 10000
    n_jobs : -1

  Lasso :
    fit_intercept : no
    penalty : l1
    solver : saga
    tol : 0.001
    max_iter : 10000
    n_jobs : -1

  ElasticNet :
    loss : log
    penalty : elasticnet
    fit_intercept : no
    tol : 0.001
    max_iter : 10000
    n_jobs : -1

  Catboost :
    od_type : Iter
    od_wait : 40

  MLP :
    monitor : val_loss
    mode : min
    epochs : 50
    iter_patience : 2
    min_delta : 0.005
    hidden_activation : relu
    out_activation : sigmoid
    loss_func : binary_crossentropy
    optimizer : adam
    weight_init : uniform

# 2.1. Grid Search Options ----------------------------------------------------------

use gridsearch : Yes

cross-validation folds : 2

cross-validation score : AUC

tuning hyperparameters :
  GLM : None

  Lasso :
    C : [0.1, 0.1207, 1000.0]

  ElasticNet :
    l1_ratio : [0.0, 0.05, 0.95]
    alpha : [0.00001, 2.5, 10.0]

  SVMC :
    C : [0.5,1]
    shrinking : [False,True]

  SVMR :
    C : [0.5,1]
    shrinking : [False,True]

  NB :
    var_smoothing : [0.000000001,0.000000002]

  Catboost :
    l2_leaf_reg : [3.,50.]
    depth : [2.,4.]
    leaf_estimation_iterations : [1.,2.]
    bagging_temperature : [0.6,1.]
    learning_rate : [0.03,0.3]

  MLP :
    batch_size : [32,64]
    num_neurons : [5,10]
    learning_rate : [0.001, 0.01]
    dropout_rate : [0.1, 0.2]
    l1_ratio : [0.0001,0.001]

# 3. Saving options ------------------------------------------------------------------
